public class Arithmetic {
    public integer addition(integer x,integer y) {
        integer sum= x+y;
        return sum;
    }

    public integer subtaction(integer n, integer z){
        integer sub=n-z;
        return sub;

    }

    public integer multiply(integer a, integer b, integer c){
        integer multi = a*b*c;
        return multi;
    }
    public string concatString(string d, string e){
        string conc = d+'&'+e;
        return conc;

    }
}