public  class CheckDatatypes {
    public void methodBoolean() {
        Boolean checkBoolean;
        system.debug(checkBoolean);
    
    }

   public void methodInteger(){
    integer varFirst=1;
    integer varSecond=2;
    system.debug(varfirst);
    system.debug(varsecond);
   }

   public void stringMethod(){
    string varName= 'Name';
    string var2name='Elif';
    system.debug(varName);
    system.debug(var2name);
   }

   public void methodId(){
   id checkId = '0013X00002RFKSHAAZ';
   system.debug(checkId);
   }

   public void methodDouble(){
    decimal varrFirst=1.23;
    double varrSecond= 209.764;
    system.debug(varrFirst);
    system.debug(varrSecond);

   }
}