public  class Player {
    public void playing() {
string player1Name='Elif Karaman';
system.debug(player1Name);
integer a =player1Name.length();
system.debug(a);
string b = player1Name.toUpperCase();
system.debug(b);

string player3Name='Refia Aksoy';
system.debug(player3Name.length());
string c =player3Name.toUpperCase();
system.debug(c);

string player2Name='Efe Kadioglu';
system.debug(player2Name.length());


string player4Name='Burak Dogan';
system.debug(player4Name + ' '+ player4Name.length());

string player5Name='Talip Gundogdu';
system.debug(player5Name+' ' + player5Name.length());

    }
}